/* the top 100 running backs of 2016 */

/* http://www.espn.com/fantasy/football/story/_/id/12872342/rb-rankings-2015 */

DECLARE @NumberOfPlayers INT = 0

SELECT @NumberOfPlayers = COUNT(1) FROM [dbo].[Players]

IF @NumberOfPlayers < 100
BEGIN

	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Adrian','Peterson')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Todd','Gurley')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Ezekiel','Elliott')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('David','Johnson')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Devonta','Freeman')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Lamar','Miller')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Doug','Martin')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Mark','Ingram')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Eddie','Lacy')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('LeSean','McCoy')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jonathan','Stewart')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Carlos','Hyde')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('C.J.','Anderson')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jamaal','Charles')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Thomas','Rawls')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Matt','Forte')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jeremy','Hill')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Latavius','Murray')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Ryan','Mathews')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('DeMarco','Murray')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jeremy','Langford')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Matt','Jones')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Melvin','Gordon')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Duke','Johnson')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Danny','Woodhead')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Frank','Gore')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Rashad','Jennings')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('T.J.','Yeldon')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Giovani','Bernard')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Arian','Foster')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Ameer','Abdullah')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Chris','Ivory')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Derrick','Henry')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('DeAngelo','Williams')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Bilal','Powell')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jay','Ajayi')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Theo','Riddick')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Charles','Sims')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Isaiah','Crowell')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('James','Starks')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('LeGarrette','Blount')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Spencer','Ware')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Terrance','West')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Tevin','Coleman')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Devontae','Booker')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Darren','Sproles')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('James','White')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jerick','McKinnon')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Christine','Michael')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Kenneth','Dixon')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Alfred','Morris')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Charcandrick','West')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Shane','Vereen')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Chris','Thompson')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('DeAndre','Washington')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('C.J.','Spiller')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Shaun','Draughn')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Tim','Hightower')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jordan','Howard')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Chris','Johnson')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('C.J.','Prosise')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Benjamin','Cunningham')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Cameron','Artis-Payne')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Javorius','Allen')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Orleans','Darkwa')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Reggie','Bush')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Lance','Dunbar')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Tyler','Ervin')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Mike','Gillislee')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('D.J.','Foster')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Robert','Turbin')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Dion','Lewis')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Paul','Perkins')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Andre','Ellington')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Kenjon','Barner')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Zach','Zenner')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Wendell','Smallwood')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Kenyan','Drake')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Brandon','Bolden')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Malcolm','Brown')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Alfred','Blue')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Mike','Davis')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Josh','Ferguson')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jalen','Richard')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('George','Atkinson')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Fozzy','Whittaker')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Antonio','Andrews')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Mike','Tolbert')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Fitzgerald','Toussaint')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jonathan','Grimes')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Jonathan','Williams')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Darren','McFadden')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Dwayne','Washington')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Alex','Collins')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Matt','Asiata')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Kapri','Bibbs')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Justin','Forsett')
	INSERT [dbo].[Players] (FirstName, LastName) VALUES ('Robert','Kelley')

END